import type { Metadata } from "next";
import "./globals.css";
import { ToastProvider } from "@/providers/ToastProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import Sidebar from "@/components/shared/Sidebar";
import ReactQueryProvider from "@/providers/ReactQuery";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <ReduxProvider>
          <ReactQueryProvider>
                 <ToastProvider />
                     <Sidebar />
                          {children}
          </ReactQueryProvider >
        </ReduxProvider>
      </body>
    </html>
  );
}
